/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oMIiFf2rlRN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "~/components/ui/button"
import { TooltipTrigger, TooltipContent, Tooltip, TooltipProvider } from "~/components/ui/tooltip"
import { PopoverTrigger, PopoverContent, Popover } from "~/components/ui/popover"
import { ArrowBigDownDash, ArrowBigUpDash } from "lucide-react"

export function tooltipV0() {
  return (
    <div className="grid grid-cols-5 place-items-center gap-x-2 ">
      <TooltipProvider>
        
      <Tooltip>
          <TooltipTrigger asChild>
            <Button className="text-black" size="icon" variant="ghost">
              <CopyIcon className="h-5 w-5" />
              <span className="sr-only">Clone</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>Clone</TooltipContent>
        </Tooltip>
        <div className="row-start-2 col-start-1 text-sm text-gray-500 dark:text-gray-400">12</div>

        <Tooltip>
          <TooltipTrigger asChild>
            <Button className="text-black" size="icon" variant="ghost">
              <ArrowBigUpDash className="h-5 w-5" />
              <span className="sr-only">Upvote</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>Upvote</TooltipContent>
        </Tooltip>
        <div className="row-start-2 col-start-2 text-sm text-gray-500 dark:text-gray-400">12</div>
        <Tooltip>
          <TooltipTrigger asChild>
            <Button className="text-black" size="icon" variant="ghost">
            <ArrowBigDownDash  className="h-5 w-5"/>
              <span className="sr-only">Downvote</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>Downvote</TooltipContent>
        </Tooltip>
        <div className="row-start-2 col-start-3 text-sm text-gray-500 dark:text-gray-400">5</div>
        
        <Tooltip>
          <TooltipTrigger asChild>
            <Button className="text-black" size="icon" variant="ghost">
              <ShareIcon className="h-5 w-5" />
              <span className="sr-only">Share</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>Share</TooltipContent>
        </Tooltip>
        <Popover>
          <PopoverTrigger asChild>
            <Button className="text-black" size="icon" variant="ghost">
              <MoveHorizontalIcon className="h-5 w-5" />
              <span className="sr-only">More</span>
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-80 p-4 grid gap-4">
            <div className="space-y-2">
              <h4 className="font-medium">Share this workout</h4>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Share this workout on your favorite social media platforms.
              </p>
              <div className="flex items-center gap-2">
                <Button className="w-10 h-10" size="icon" variant="outline">
                  <FacebookIcon className="h-5 w-5" />
                </Button>
                <Button className="w-10 h-10" size="icon" variant="outline">
                  <TwitterIcon className="h-5 w-5" />
                </Button>
                <Button className="w-10 h-10" size="icon" variant="outline">
                  <InstagramIcon className="h-5 w-5" />
                </Button>
                <Button className="w-10 h-10" size="icon" variant="outline">
                  <LinkedinIcon className="h-5 w-5" />
                </Button>
              </div>
            </div>
          </PopoverContent>
        </Popover>
      </TooltipProvider>
    </div>
  )
}

function ArrowDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>
  )
}


function ArrowUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function CopyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}


function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
