/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qbtk4OhRlhV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function v0showcase() {
  return (
    <div className="bg-gradient-to-br from-[#FFF5F5] to-[#FFF1F1] dark:from-[#1E1E1E] dark:to-[#171717] rounded-lg shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)] p-6 max-w-3xl mx-auto">
      <h2 className="text-2xl font-bold mb-6 text-[#006400] dark:text-[#00FF00]">
        4-Day Workout Routine with Rest Days
      </h2>
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <h3 className="text-xl font-bold mb-2 text-[#006400] dark:text-[#00FF00]">Day 1 - Chest & Triceps</h3>
            <div className="space-y-4">
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Bench Press</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 8-10 reps (Targets chest and triceps)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Dumbbell Flyes</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 10-12 reps (Targets chest)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Tricep Pushdowns</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 12-15 reps (Targets triceps)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Skull Crushers</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 10-12 reps (Targets triceps)</p>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <h3 className="text-xl font-bold mb-2 text-[#006400] dark:text-[#00FF00]">Day 2 - Back & Biceps</h3>
            <div className="space-y-4">
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Lat Pulldowns</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 10-12 reps (Targets back)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Seated Cable Rows</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 8-10 reps (Targets back)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Barbell Curls</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 10-12 reps (Targets biceps)</p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Hammer Curls</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">3 sets of 10-12 reps (Targets biceps)</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)] text-center">
          <h3 className="text-xl font-bold mb-2 text-[#006400] dark:text-[#00FF00]">Day 3 - Rest Day</h3>
          <p className="text-[#707070] dark:text-[#9E9E9E]">Take a break and rest your muscles.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <h3 className="text-xl font-bold mb-2 text-[#006400] dark:text-[#00FF00]">Day 4 - Legs</h3>
            <div className="space-y-4">
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Squats</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">
                    3 sets of 8-10 reps (Targets quadriceps, glutes, and hamstrings)
                  </p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Deadlifts</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">
                    3 sets of 6-8 reps (Targets back, hamstrings, and glutes)
                  </p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Lunges</h4>
                  <p className="text-[#707070] dark:text-[#9E9E9E]">
                    3 sets of 10-12 reps per leg (Targets quadriceps, glutes, and hamstrings)
                  </p>
                </div>
              </div>
              <div className="flex items-center">
                <div className="mr-4 w-10 h-10 bg-gradient-to-br from-[#D9D9D9] to-[#CFCFCF] dark:from-[#3A3A3A] dark:to-[#323232] rounded-md flex items-center justify-center">
                  <PlayIcon className="w-6 h-6 text-[#8C8C8C] dark:text-[#A0A0A0]" />
                </div>
                <div>
                  <h4 className="text-base font-medium mb-1 text-[#333333] dark:text-[#CCCCCC]">Calf Raises</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}
