/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4nWRrxF7qJ5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Rubik } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Skeleton } from "~/components/ui/skeleton"

export function v0skeleton() {
  return (
    <div className="bg-gradient-to-br from-[#FFF5F5] to-[#FFF1F1] dark:from-[#1E1E1E] dark:to-[#171717] rounded-lg shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)] p-6 max-w-3xl mx-auto">
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <Skeleton className="h-6 w-full mb-4" />
            <div className="space-y-4">
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <Skeleton className="h-6 w-full mb-4" />
            <div className="space-y-4">
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)] text-center">
          <Skeleton className="h-6 w-full mb-4" />
          <Skeleton className="h-4 w-48" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <Skeleton className="h-6 w-full mb-4" />
            <div className="space-y-4">
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gradient-to-br from-[#F0F0F0] to-[#E6E6E6] dark:from-[#2A2A2A] dark:to-[#232323] rounded-lg p-4 shadow-[0_10px_15px_-3px_rgba(0,0,0,0.1),0_4px_6px_-2px_rgba(0,0,0,0.05)]">
            <Skeleton className="h-6 w-full mb-4" />
            <div className="space-y-4">
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
              <div className="flex items-center">
                <Skeleton className="h-10 w-10 mr-4 rounded-md" />
                <div>
                  <Skeleton className="h-4 w-32 mb-2" />
                  <Skeleton className="h-4 w-48" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
