import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import '~/styles/bgPattern.css'
import { Button } from "~/components/ui/button";
import { inter } from "~/components/ui/font";
import Footer from "~/components/ui/footer";
import SessionWrapper from "~/lib/SessionWrapper";
import { Toaster } from "~/components/ui/sonner";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata = {
  title: "ProloadT3",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
    <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
      <body className={`${inter.className} bg-white`} >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <main>
        {children}
        </main>
        <Toaster />
        </ThemeProvider>
        </body>
        
    </html>
    </SessionWrapper>
  );
}
